# Generated by Django 5.0.6 on 2024-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_code', models.CharField(max_length=25)),
                ('high', models.DecimalField(decimal_places=1, max_digits=5)),
                ('low', models.DecimalField(decimal_places=1, max_digits=5)),
                ('open', models.DecimalField(decimal_places=1, max_digits=5)),
                ('close', models.DecimalField(decimal_places=1, max_digits=5)),
                ('volume', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
